--1 CONFIRMATION OF TABLES

SELECT * 

FROM DEATHS
WHERE CONTINENT IS NOT NULL
ORDER BY 3 ,4

SELECT *
FROM PORTFOLIOPROJECT..VACCINATIONS

----------------------------------

SELECT LOCATION, DATE, TOTAL_CASES, NEW_cases, total_deaths, [population]
from deaths
WHERE CONTINENT IS NOT NULL
order by 1,2
----------------------------------------------------------- MOZAMBIQUE DATA INFORMATION ON DEATHS AND NEW CASES
SELECT [LOCATION], DATE, TOTAL_CASES, NEW_CASES, TOTAL_DEATHS, [POPULATION]
FROM DEATHS
WHERE LOCATION LIKE '%MOZ%'

---------------------------
------------ UPDATING COLUMN TYPES TO BE ABLE TO CALCULATE

alter table PORTFOLIOPROJECT..DEATHS
   alter column Total_Cases decimal(15)

alter table PORTFOLIOPROJECT..DEATHS
   alter column Total_Deaths decimal(38)



--- looking at total cases vs total deaths IN MOZAMBIQUE
---- probabilidade de morte apos a contracao de covid em Marco de 2023-16 0.96%

SELECT LOCATION, DATE, TOTAL_CASES,  total_deaths, ([total_deaths]/[total_cases])*100 as DeathPercentage
from deaths
WHERE LOCATION LIKE '%MOZ%'
order by 1 ,2 DESC

----

------------Looking at total cases vs population
--------------Showcase da percentagem da populacao que contraiu covid

SELECT LOCATION, DATE, TOTAL_CASES,  population, ([total_cases]/[population])*100 as DeathPercentage
from deaths
WHERE LOCATION LIKE '%MOZ%'
order by 1 ,2 

-------------
--Looking at countries with highest infection rate compared to population
SELECT [LOCATION],  [population], Max(TOTAL_CASES) as [HIGHESTINFECTIONCOUNT], MAX([total_cases]/[population])*100 as DeathPercentage
from deaths
group by population, location
order by 4 desc


------- COUNTRIES WITH HIGHEST DEATHCOUNT PER POPULATION
SELECT [LOCATION], Max(TOTAL_DEATHS) as [TOTALDEATHCOUNT], MAX([total_DEATHS]/[population])*100 as DeathPercentage
from deaths
WHERE CONTINENT IS NOT NULL
group by  location
ORDER BY TOTALDEATHCOUNT DESC


-- BREAKING THINGS DOWN --
--- Showing the continent with the highest death count

SELECT [location], Max(TOTAL_DEATHS) as [TOTALDEATHCOUNT]
from deaths
WHERE CONTINENT IS  NULL
group by  location
ORDER BY TOTALDEATHCOUNT DESC

--------------GLOBAL NUMBERS---

--GLOBAL DEATH RATE OVER THE CASES PER DAY

 SELECT [DATE], SUM(NEW_CASES) AS CASESDAILY , SUM(CAST(NEW_DEATHS AS INT)) AS DEATHSDAILY, SUM(CAST(NEW_DEATHS AS INT))/SUM(NEW_CASES)*100 AS [DEATH%]
from deaths
WHERE [CONTINENT] IS NOT NULL
 GROUP BY DATE
 HAVING SUM(NEW_CASES) > 0 AND SUM(CAST(NEW_DEATHS AS INT)) > 0
order by 1,2 

--GLOBAL DEATH RATE OVER THE CASES SINCE BEGGINING OF COUNTING

 SELECT  SUM(NEW_CASES) AS CASESDAILY , SUM(CAST(NEW_DEATHS AS INT)) AS DEATHSDAILY, SUM(CAST(NEW_DEATHS AS INT))/SUM(NEW_CASES)*100 AS [DEATH%]
from deaths
WHERE [CONTINENT] IS NOT NULL
 
 HAVING SUM(NEW_CASES) > 0 AND SUM(CAST(NEW_DEATHS AS INT)) > 0
order by 1,2 

-----------------------------------------------------------------------------
-----------------------------------------------------------------------------
-----------------------------------------------------------------------------




-- LOOKING AT TOTAL POPULATION VS VACCINATION
SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATE, DEA.population, VAC.NEW_VACCINATIONS, 
SUM(CAST(VAC.nEW_VACCINATIONS AS DECIMAL(20))) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) AS GROWTHVACCOUNT --(GROWTHVACCOUNT/DEATHS.population)*100 AS VACCINATIONvsPOPULATION
FROM VACCINATIONS VAC
JOIN DEATHS DEA

ON DEA.location = VAC.location AND
   DEA.date=VAC.date
   WHERE DEA.continent IS NOT NULL 
   ORDER BY 2,3



   --CTE

   WITH POPVSVAC (CONTINENT, LOCATION, DATE, POPULATION, NEW_VACCINATIONS, ROLLINGPEOPLEVACCINATED)



   AS 

   (SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATE, DEA.population, VAC.NEW_VACCINATIONS, 
SUM(CAST(VAC.nEW_VACCINATIONS AS DECIMAL(20))) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) 
AS GROWTHVACCOUNT --(GROWTHVACCOUNT/DEATHS.population)*100 AS VACCINATIONvsPOPULATION
FROM VACCINATIONS VAC
JOIN DEATHS DEA

ON DEA.location = VAC.location AND
   DEA.date=VAC.date
   WHERE DEA.continent IS NOT NULL )
  -- ORDER BY 2,3)

   SELECT *, ([ROLLINGPEOPLEVACCINATED]/POPULATION)*100
   FROM POPVSVAC


   --------

   --TEMP TABLE 

   DROP TABLE IF EXISTS #PERCENTPOPULATIONVACCINATED
   CREATE TABLE  #PERCENTPOPULATIONVACCINATED
   (
   CONTINENT NVARCHAR (255),
   LOCATION NVARCHAR (255),
   dATE DATETIME,
   POPULATION NUMERIC,
   NEWVACCINATION NUMERIC,
   ROLLINGPEOPLEVACCINATED NUMERIC)

   INSERT INTO #PERCENTPOPULATIONVACCINATED

   SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATE, DEA.population, VAC.NEW_VACCINATIONS, 
SUM(CAST(VAC.nEW_VACCINATIONS AS DECIMAL(20))) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) 
AS GROWTHVACCOUNT --(GROWTHVACCOUNT/DEATHS.population)*100 AS VACCINATIONvsPOPULATION
FROM VACCINATIONS VAC
JOIN DEATHS DEA

ON DEA.location = VAC.location AND
   DEA.date=VAC.date
WHERE DEA.continent IS NOT NULL
  -- ORDER BY 2,3)

   SELECT *, ([ROLLINGPEOPLEVACCINATED]/POPULATION)*100 AS [ROLLINGPEOPLEVACCINATED%]
   FROM #PERCENTPOPULATIONVACCINATED


   -----------------------------
   -----------------------------
   -----------------------------

   -- CREATING OUR VIEW TO STORE DATA FOR LATER, VISUALIZATIONS.


   CREATE VIEW PERCENTPOPULATIONVACCINATED AS 

      SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATE, DEA.population, VAC.NEW_VACCINATIONS, 
SUM(CAST(VAC.nEW_VACCINATIONS AS DECIMAL(20))) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) 
AS GROWTHVACCOUNT --(GROWTHVACCOUNT/DEATHS.population)*100 AS VACCINATIONvsPOPULATION
FROM VACCINATIONS VAC
JOIN DEATHS DEA

ON DEA.location = VAC.location AND
   DEA.date=VAC.date
WHERE DEA.continent IS NOT NULL
  -- ORDER BY 2,3)

  SELECT * FROM PERCENTPOPULATIONVACCINATED

  DELETE PERCENTPOPULATIONVACCINATED